name: utp
description: uTP library wirtten by Dart. It implements BitTorren BEP0029 Specification.
version: 0.2.0
repository: https://github.com/eclipseglory/utp
issue_tracker : https://github.com/eclipseglory/utp/issues
publish_to: https://pub.dev/

environment:
  sdk: '>=2.10.0 <3.0.0'

# dependencies:

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
